[FIX] AttributeError: 'dict' object has no attribute '_zc_recipe_egg_working_set_cache', internal implementation of zc.recipe.egg has changed since version >= 2.0.4. Changing the 'self.buildout' attribute of the recipe to an object with a dict interface (to be retrocompatible) fixes the situation